[build]
command = "yarn build"
functions = "netlify/functions"
publish = ".next"

[[edge_functions]]
function = "localize"
path = "/*"

[[edge_functions]]
function = "hello"
path = "/hello"

#CHAIN EXAMPLES

# [[edge_functions]]
# function = "auth"
# path = "/admin"

# [[edge_functions]]
# function = "injector"
# path = "/admin"

# [[edge_functions]]
# function = "auth"
# path = "/blog/*"

# [[edge_functions]]
# function = "rewriter"
# path = "/blog/*"

# [[edge_functions]]
# function = "common"
# path = "/*"
