import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home({ country, user, date }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {user} from {country}
        </h1>
        <p>{date}</p>
      </main>
      <footer className={styles.footer}></footer>
      <form action="/api/hello">
        <input type="email" />
      </form>
    </div>
  );
}

export function getServerSideProps({ req, res }) {
  // console.log('headers', req.headers);
  // console.log('cookies', req.cookies.user);
  return {
    props: {
      country: req.cookies.country_code || 'nonso',
      user: req.cookies.user || 'boh',
      date: `${new Date().toLocaleString()}`,
    },
  };
}
